#ifndef PINS_H
#define PINS_H

#include "driver/gpio.h"

#define TERMOCOUPLE_PIN_MISO  GPIO_NUM_13
#define TERMOCOUPLE_PIN_MOSI  GPIO_NUM_11 //not connected
#define TERMOCOUPLE_PIN_CLK   GPIO_NUM_12
#define TERMOCOUPLE_PIN_CS    GPIO_NUM_10
#define TERMOCOUPLE_DMA_CHAN  SPI_DMA_CH_AUTO
#define TERMOCOUPLE_SPI_HOST  SPI2_HOST
#define DISPLAY_TXD_PIN GPIO_NUM_17
#define DISPLAY_RXD_PIN GPIO_NUM_16
#define DISPLAY_UART UART_NUM_2

#define WATERFLOW_PULSE_PIN GPIO_NUM_35
#define HEATER_PIN_A  GPIO_NUM_4
#define HEATER_PIN_B  GPIO_NUM_5
#define HEATER_PIN_C  GPIO_NUM_6

#define WIFI_LED_PIN  GPIO_NUM_2


#define JTAG_TMS  GPIO_NUM_42
#define JTAG_TCK  GPIO_NUM_39
#define JTAG_TDO  GPIO_NUM_40
#define JTAG_TDI  GPIO_NUM_41
#endif 