#ifndef PINS_H
#define PINS_H

#include "driver/gpio.h"

#define TERMOCOUPLE_PIN_MISO  GPIO_NUM_19
#define TERMOCOUPLE_PIN_MOSI  GPIO_NUM_23 //not connected
#define TERMOCOUPLE_PIN_CLK   GPIO_NUM_18
#define TERMOCOUPLE_PIN_CS    GPIO_NUM_25
#define TERMOCOUPLE_DMA_CHAN    2

#define DISPLAY_TXD_PIN GPIO_NUM_17
#define DISPLAY_RXD_PIN GPIO_NUM_16
#define DISPLAY_UART UART_NUM_2

#define WATERFLOW_PULSE_PIN GPIO_NUM_35

#define HEATER_PIN_A  GPIO_NUM_32
#define HEATER_PIN_B  GPIO_NUM_33
#define HEATER_PIN_C  GPIO_NUM_26

#define WIFI_LED_PIN  GPIO_NUM_2


#define JTAG_TMS  GPIO_NUM_14
#define JTAG_TCK  GPIO_NUM_13
#define JTAG_TDO  GPIO_NUM_15
#define JTAG_TDI  GPIO_NUM_12
#endif 